name: Deploy Go API
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/user-api:${{ github.sha }},${{ secrets.DOCKER_USERNAME }}/user-api:latest

      - name: Deploy to Kubernetes
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Update the image
            kubectl set image deployment/user-api -n apps user-api=${{ secrets.DOCKER_USERNAME }}/user-api:${{ github.sha }}
            
            # Wait for rollout to complete
            kubectl rollout status deployment/user-api -n apps --timeout=300s
            
            echo "Deployment completed successfully!"